name: Splitbot Lints

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 bandit pylint black
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=79 --statistics
    - name: Bandit syntax check
      run: bandit -r . -b .bandit_baseline.json
    - name: Pylint
      run: pylint ./bot.py cogs/*.py core/*.py utils/*.py --exit-zero -r y --disable=C0114,C0115,C0116
    - name: Black
      run: |
        black . --diff --check --line-length=79
